repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: ['--allow-multiple-documents', '--unsafe']
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        args:
            - '-l 120'
            - '--check'
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args:
            - --profile
            - black
            - --check-only
            - --diff
            - -v
-   repo: https://github.com/PyCQA/autoflake.git # autoflake removes unused imports and unused variables from Python code.
    rev: v2.0.0
    hooks:
    -   id: autoflake
        args:
            - --remove-all-unused-imports
            - --remove-unused-variable
            - --expand-star-imports
            - --ignore-init-module-imports
            - --check-diff
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
    -   id: pylint
        args:
            #- --rcfile=standard.rc
            - --max-line-length=120
            - --ignore-imports=yes
            - --disable=C0103 # Module name doesn't conform to snake_case naming style (invalid-name)
            - --disable=broad-except # disable broad-except
            - --disable=E0401 # Unable to import
            - --disable=R0903 # too-few-public-methods
            - --disable=C0415 # import-outside-toplevel
            - --disable=W1514 # Using open without explicitly specifying an encoding (unspecified-encoding)
            - --enable=similarities
            - --min-similarity-lines=35 # code duplication: decrease this value to find less similar lines
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
        args: ["--exit-code", "--list-fixes"]
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.7.2
    hooks:
    -   id: shellcheck
-   repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
    -   id: hadolint-docker
        args:
        - "--style"
        - "DL3008"
        - "--style"
        - "DL3015"
