repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
        args:
        - "-vvv"
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args:
            - --profile
            - black
-   repo: https://github.com/myint/autoflake.git # autoflake removes unused imports and unused variables from Python code.
    rev: v1.4
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable', '--expand-star-imports', '--ignore-init-module-imports']

-   repo: https://github.com/asottile/pyupgrade # A tool (and pre-commit hook) to automatically upgrade syntax for newer versions of the language.
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        args:
            - '-l 120'
